// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScheduleCreator.EntityFramework;

namespace ScheduleCreator.EntityFramework.Migrations
{
    [DbContext(typeof(ScheduleCreatorDbContext))]
    [Migration("20210215132006_CompleteRelationships")]
    partial class CompleteRelationships
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ScheduleCreator.Domain.Models.Date", b =>
                {
                    b.Property<int>("DateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FreeDayChosen")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PreferencesId")
                        .HasColumnType("int");

                    b.HasKey("DateId");

                    b.HasIndex("PreferencesId");

                    b.ToTable("Dates");
                });

            modelBuilder.Entity("ScheduleCreator.Domain.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("PreferencesId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("PreferencesId")
                        .IsUnique()
                        .HasFilter("[PreferencesId] IS NOT NULL");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ScheduleCreator.Domain.Models.EmployeeSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("EmployeeSchedules");
                });

            modelBuilder.Entity("ScheduleCreator.Domain.Models.Preferences", b =>
                {
                    b.Property<int>("PreferencesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short>("FreeWorkingDays")
                        .HasColumnType("smallint");

                    b.HasKey("PreferencesId");

                    b.ToTable("Preferences");
                });

            modelBuilder.Entity("ScheduleCreator.Domain.Models.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short>("Month")
                        .HasColumnType("smallint");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<short>("WorkingDays")
                        .HasColumnType("smallint");

                    b.Property<byte>("Year")
                        .HasColumnType("tinyint");

                    b.HasKey("ScheduleId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("ScheduleCreator.Domain.Models.Date", b =>
                {
                    b.HasOne("ScheduleCreator.Domain.Models.Preferences", "Preferences")
                        .WithMany("Dates")
                        .HasForeignKey("PreferencesId");
                });

            modelBuilder.Entity("ScheduleCreator.Domain.Models.Employee", b =>
                {
                    b.HasOne("ScheduleCreator.Domain.Models.Preferences", "Preferences")
                        .WithOne("Employee")
                        .HasForeignKey("ScheduleCreator.Domain.Models.Employee", "PreferencesId");
                });

            modelBuilder.Entity("ScheduleCreator.Domain.Models.EmployeeSchedule", b =>
                {
                    b.HasOne("ScheduleCreator.Domain.Models.Employee", "Employee")
                        .WithMany("EmployeeSchedules")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScheduleCreator.Domain.Models.Schedule", "Schedule")
                        .WithMany("EmployeeSchedules")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
