// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScheduleCreator.EntityFramework;

namespace ScheduleCreator.EntityFramework.Migrations
{
    [DbContext(typeof(ScheduleCreatorDbContext))]
    [Migration("20210613121401_NewValueInPreferences")]
    partial class NewValueInPreferences
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("ScheduleCreator.Domain.Models.Day", b =>
                {
                    b.Property<int>("DayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWorking")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MonthId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WorkingDay")
                        .HasColumnType("TEXT");

                    b.HasKey("DayId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Days");
                });

            modelBuilder.Entity("ScheduleCreator.Domain.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PreferencesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EmployeeId");

                    b.HasIndex("PreferencesId")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ScheduleCreator.Domain.Models.PreferenceDay", b =>
                {
                    b.Property<int>("PreferenceDayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FreeDayChosen")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PreferencesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PreferenceDayId");

                    b.HasIndex("PreferencesId");

                    b.ToTable("PreferenceDays");
                });

            modelBuilder.Entity("ScheduleCreator.Domain.Models.Preferences", b =>
                {
                    b.Property<int>("PreferencesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<sbyte>("FreeWorkingDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("From")
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalPreferenceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LeaveDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("To")
                        .HasColumnType("TEXT");

                    b.HasKey("PreferencesId");

                    b.ToTable("Preferences");
                });

            modelBuilder.Entity("ScheduleCreator.Domain.Models.Day", b =>
                {
                    b.HasOne("ScheduleCreator.Domain.Models.Employee", "Employee")
                        .WithMany("Days")
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ScheduleCreator.Domain.Models.Employee", b =>
                {
                    b.HasOne("ScheduleCreator.Domain.Models.Preferences", "Preferences")
                        .WithOne("Employee")
                        .HasForeignKey("ScheduleCreator.Domain.Models.Employee", "PreferencesId");

                    b.Navigation("Preferences");
                });

            modelBuilder.Entity("ScheduleCreator.Domain.Models.PreferenceDay", b =>
                {
                    b.HasOne("ScheduleCreator.Domain.Models.Preferences", "Preferences")
                        .WithMany("PreferenceDays")
                        .HasForeignKey("PreferencesId");

                    b.Navigation("Preferences");
                });

            modelBuilder.Entity("ScheduleCreator.Domain.Models.Employee", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("ScheduleCreator.Domain.Models.Preferences", b =>
                {
                    b.Navigation("Employee");

                    b.Navigation("PreferenceDays");
                });
#pragma warning restore 612, 618
        }
    }
}
