// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScheduleCreator.EntityFramework;

namespace ScheduleCreator.EntityFramework.Migrations
{
    [DbContext(typeof(ScheduleCreatorDbContext))]
    [Migration("20210318183137_test3")]
    partial class test3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ScheduleCreator.Domain.Models.Date", b =>
                {
                    b.Property<int>("DateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FreeDayChosen")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PreferencesId")
                        .HasColumnType("int");

                    b.HasKey("DateId");

                    b.HasIndex("PreferencesId");

                    b.ToTable("Dates");
                });

            modelBuilder.Entity("ScheduleCreator.Domain.Models.Day", b =>
                {
                    b.Property<int>("DayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int?>("WeekId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WorkingDay")
                        .HasColumnType("datetime2");

                    b.HasKey("DayId");

                    b.HasIndex("WeekId");

                    b.ToTable("Day");
                });

            modelBuilder.Entity("ScheduleCreator.Domain.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PreferencesId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("PreferencesId")
                        .IsUnique()
                        .HasFilter("[PreferencesId] IS NOT NULL");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ScheduleCreator.Domain.Models.EmployeeSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("EmployeeSchedules");
                });

            modelBuilder.Entity("ScheduleCreator.Domain.Models.Preferences", b =>
                {
                    b.Property<int>("PreferencesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short>("FreeWorkingDays")
                        .HasColumnType("smallint");

                    b.Property<string>("InternalPreferenceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PreferencesId");

                    b.ToTable("Preferences");
                });

            modelBuilder.Entity("ScheduleCreator.Domain.Models.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short>("Month")
                        .HasColumnType("smallint");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<short>("WorkingDays")
                        .HasColumnType("smallint");

                    b.Property<byte>("Year")
                        .HasColumnType("tinyint");

                    b.HasKey("ScheduleId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("ScheduleCreator.Domain.Models.Week", b =>
                {
                    b.Property<int>("WeekId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("InternalWeekId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("WorkingDays")
                        .HasColumnType("tinyint");

                    b.HasKey("WeekId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Week");
                });

            modelBuilder.Entity("ScheduleCreator.Domain.Models.Date", b =>
                {
                    b.HasOne("ScheduleCreator.Domain.Models.Preferences", "Preferences")
                        .WithMany("Dates")
                        .HasForeignKey("PreferencesId");

                    b.Navigation("Preferences");
                });

            modelBuilder.Entity("ScheduleCreator.Domain.Models.Day", b =>
                {
                    b.HasOne("ScheduleCreator.Domain.Models.Week", "Week")
                        .WithMany("Days")
                        .HasForeignKey("WeekId");

                    b.Navigation("Week");
                });

            modelBuilder.Entity("ScheduleCreator.Domain.Models.Employee", b =>
                {
                    b.HasOne("ScheduleCreator.Domain.Models.Preferences", "Preferences")
                        .WithOne("Employee")
                        .HasForeignKey("ScheduleCreator.Domain.Models.Employee", "PreferencesId");

                    b.Navigation("Preferences");
                });

            modelBuilder.Entity("ScheduleCreator.Domain.Models.EmployeeSchedule", b =>
                {
                    b.HasOne("ScheduleCreator.Domain.Models.Employee", "Employee")
                        .WithMany("EmployeeSchedules")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScheduleCreator.Domain.Models.Schedule", "Schedule")
                        .WithMany("EmployeeSchedules")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("ScheduleCreator.Domain.Models.Week", b =>
                {
                    b.HasOne("ScheduleCreator.Domain.Models.Employee", "Employee")
                        .WithMany("Weeks")
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ScheduleCreator.Domain.Models.Employee", b =>
                {
                    b.Navigation("EmployeeSchedules");

                    b.Navigation("Weeks");
                });

            modelBuilder.Entity("ScheduleCreator.Domain.Models.Preferences", b =>
                {
                    b.Navigation("Dates");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ScheduleCreator.Domain.Models.Schedule", b =>
                {
                    b.Navigation("EmployeeSchedules");
                });

            modelBuilder.Entity("ScheduleCreator.Domain.Models.Week", b =>
                {
                    b.Navigation("Days");
                });
#pragma warning restore 612, 618
        }
    }
}
