// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScheduleCreator.EntityFramework;

namespace ScheduleCreator.EntityFramework.Migrations
{
    [DbContext(typeof(ScheduleCreatorDbContext))]
    partial class ScheduleCreatorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("ScheduleCreator.Domain.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkingDays")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("ScheduleCreator.Domain.Models.Schedule", b =>
                {
                    b.OwnsMany("ScheduleCreator.Domain.Models.Employee", "Employees", b1 =>
                        {
                            b1.Property<int>("ScheduleId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("LastName")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Shift")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("WorkingDays")
                                .HasColumnType("INTEGER");

                            b1.HasKey("ScheduleId", "Id");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("ScheduleId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
